[package]
name = "codex-git-utils"
version = "0.156.1"
edition = "2024"
license = "Apache-2.0"
readme = "README.md"

[lib]
doctest = false

[dependencies.anyhow]
version = "1"

[dependencies.chrono]
version = "0.4.43"

[dependencies.codex-file-system]
git = "https://github.com/openai/codex.git"
rev = "b412ff32c417f855c2b2d1581b77058eed87c84b"

[dependencies.codex-protocol]
git = "https://github.com/openai/codex.git"
rev = "b412ff32c417f855c2b2d1581b77058eed87c84b"

[dependencies.codex-utils-absolute-path]
git = "https://github.com/openai/codex.git"
rev = "b412ff32c417f855c2b2d1581b77058eed87c84b"

[dependencies.codex-utils-path-uri]
git = "https://github.com/openai/codex.git"
rev = "b412ff32c417f855c2b2d1581b77058eed87c84b"

[dependencies.codex-utils-pty]
git = "https://github.com/openai/codex.git"
rev = "b412ff32c417f855c2b2d1581b77058eed87c84b"

[dependencies.futures]
version = "0.3"
default-features = false
features = [ "alloc",]

[dependencies.gix]
version = "0.81.0"
default-features = false
features = [ "sha1",]

[dependencies.once_cell]
version = "1.20.2"

[dependencies.regex]
version = "1"

[dependencies.schemars]
version = "0.8.22"

[dependencies.serde]
version = "1"
features = [ "rc", "derive",]

[dependencies.similar]
version = "2.7.0"

[dependencies.tempfile]
version = "3.23.0"

[dependencies.thiserror]
version = "2.0.17"

[dependencies.tokio]
version = "1"
features = [ "macros", "process", "rt", "time",]

[dependencies.ts-rs]
version = "11"
features = [ "uuid-impl", "serde-json-impl", "no-serde-warnings",]

[dependencies.walkdir]
version = "2.5.0"
