[package]
name = "codex-shell-command"
version = "0.156.1"
edition = "2024"
license = "Apache-2.0"

[lib]
doctest = false

[dependencies.base64]
version = "0.22.1"

[dependencies.codex-protocol]
git = "https://github.com/openai/codex.git"
rev = "b412ff32c417f855c2b2d1581b77058eed87c84b"

[dependencies.codex-utils-absolute-path]
git = "https://github.com/openai/codex.git"
rev = "b412ff32c417f855c2b2d1581b77058eed87c84b"

[dependencies.libc]
version = "0.2.182"

[dependencies.once_cell]
version = "1.20.2"

[dependencies.regex]
version = "1.12.3"

[dependencies.serde]
version = "1"
features = [ "rc", "derive",]

[dependencies.serde_json]
version = "1"

[dependencies.shlex]
version = "1.3.0"

[dependencies.tree-sitter]
version = "0.25.10"

[dependencies.tree-sitter-bash]
version = "0.25"

[dependencies.tree-sitter-powershell]
version = "=0.26.4"

[dependencies.url]
version = "2"

[dependencies.which]
version = "8"
