mod authority;
mod binding;
mod cancellation;
mod capability;
mod capability_intents;
mod capability_metadata;
mod capability_registry;
mod capability_response;
mod capability_schema;
mod credential;
mod delivery;
mod diagnostics;
mod features;
mod gateway;
mod handler;
mod http;
mod invocation;
mod lease;
mod plugin_catalog;
mod policy;
mod receipt;
mod result;
mod runtime;
mod service;
mod session;
mod tool_identity;

pub use authority::{SessionAuthority, SessionIdentity};
pub use credential::SessionToken;
pub use features::{FeatureSnapshot, MemoryCapability, MemoryPermissions};
pub use lease::BuiltinMcpIssueError;
pub use service::{BuiltinMcpClient, BuiltinMcpService};
pub(crate) use tool_identity::{invoked_tool_name, GatewayToolIdentity};
