[package]
name = "codex-hooks"
version = "0.156.1"
edition = "2024"
license = "Apache-2.0"
autobins = false
autotests = false
autobenches = false

[lib]
doctest = false
name = "codex_hooks"
path = "src/lib.rs"

[dependencies.anyhow]
version = "1"

[dependencies.async-channel]
version = "2.3.1"

[dependencies.chrono]
version = "0.4.43"
features = [ "serde",]

[dependencies.codex-config]
git = "https://github.com/openai/codex.git"
rev = "b412ff32c417f855c2b2d1581b77058eed87c84b"

[dependencies.codex-plugin]
git = "https://github.com/openai/codex.git"
rev = "b412ff32c417f855c2b2d1581b77058eed87c84b"

[dependencies.codex-protocol]
git = "https://github.com/openai/codex.git"
rev = "b412ff32c417f855c2b2d1581b77058eed87c84b"

[dependencies.codex-utils-absolute-path]
git = "https://github.com/openai/codex.git"
rev = "b412ff32c417f855c2b2d1581b77058eed87c84b"

[dependencies.codex-utils-output-truncation]
git = "https://github.com/openai/codex.git"
rev = "b412ff32c417f855c2b2d1581b77058eed87c84b"

[dependencies.codex-utils-path-uri]
git = "https://github.com/openai/codex.git"
rev = "b412ff32c417f855c2b2d1581b77058eed87c84b"

[dependencies.futures]
version = "0.3"
default-features = false
features = [ "alloc",]

[dependencies.regex]
version = "1.12.3"

[dependencies.schemars]
version = "0.8.22"

[dependencies.serde]
version = "1"
features = [ "rc", "derive",]

[dependencies.serde_json]
version = "1"

[dependencies.tokio]
version = "1"
features = [ "fs", "io-util", "process", "sync", "time",]

[dependencies.tracing]
version = "0.1.44"

[dependencies.uuid]
version = "1"
features = [ "v4",]

[target."cfg(any(unix, windows))".dependencies.codex-utils-pty]
git = "https://github.com/openai/codex.git"
rev = "b412ff32c417f855c2b2d1581b77058eed87c84b"
