[package]
name = "appcontainer_common"
version = "0.8.0"
edition = "2021"
license = "MIT"
autobins = false
autotests = false
autobenches = false

[lib]
path = "src/lib.rs"
doctest = false

[dependencies."getrandom"]
version = "^0.2"

[dependencies."serde"]
version = "^1"
features = ["derive"]

[dependencies."serde_json"]
version = "^1"

[dependencies."thiserror"]
version = "^2"

[dependencies."wxc_common"]
version = "*"
git = "https://github.com/microsoft/mxc"
rev = "6cd3d58f05d3447e67109cfb75e042803b843ca4"

[target."cfg(target_os = \"windows\")".dependencies."flatbuffers"]
version = "^25"

[target."cfg(target_os = \"windows\")".dependencies."learning_mode_core"]
version = "*"
git = "https://github.com/microsoft/mxc"
rev = "6cd3d58f05d3447e67109cfb75e042803b843ca4"

[target."cfg(target_os = \"windows\")".dependencies."learning_mode_windows"]
version = "*"
git = "https://github.com/microsoft/mxc"
rev = "6cd3d58f05d3447e67109cfb75e042803b843ca4"

[target."cfg(target_os = \"windows\")".dependencies."process_security_environment_spec"]
version = "*"
git = "https://github.com/microsoft/mxc"
rev = "6cd3d58f05d3447e67109cfb75e042803b843ca4"

[target."cfg(target_os = \"windows\")".dependencies."sandbox_spec"]
version = "*"
git = "https://github.com/microsoft/mxc"
rev = "6cd3d58f05d3447e67109cfb75e042803b843ca4"

[target."cfg(target_os = \"windows\")".dependencies."widestring"]
version = "^1"

[target."cfg(target_os = \"windows\")".dependencies."windows"]
version = "^0.62"
features = ["Win32_Foundation","Win32_Networking_WinSock","Win32_NetworkManagement_WindowsFirewall","Win32_Security","Win32_Security_Authorization","Win32_Security_Credentials","Win32_Security_Isolation","Win32_Storage_FileSystem","Win32_System_Com","Win32_System_Console","Win32_System_Diagnostics_Debug","Win32_System_Diagnostics_Etw","Win32_System_Diagnostics_ToolHelp","Win32_System_Environment","Win32_System_IO","Win32_System_JobObjects","Win32_System_LibraryLoader","Win32_System_Memory","Win32_System_Ole","Win32_System_Pipes","Win32_System_ProcessStatus","Win32_System_Registry","Win32_System_SystemInformation","Win32_System_SystemServices","Win32_System_Threading","Win32_System_Time","Win32_System_Variant","Win32_System_WindowsProgramming","Win32_UI_Shell"]

[target."cfg(target_os = \"windows\")".dependencies."windows-core"]
version = "^0.62"

[target."cfg(target_os = \"windows\")".dependencies."winreg"]
version = "^0.55"

[features]
"tier2_bfs" = []
