pub(super) const LESSON_INSTRUCTIONS: &str = r#"## Experience review before finishing

After substantive work, privately check for a specific reusable lesson supported by an observed result and verification. When a Skill was used, include the Skill's stable name in `context` and record whether it succeeded, failed, or needed a correction; capture the concrete verification that supports that judgment. Repeated verified successes can guide future Skill use, while failures should guide a safer alternative or correction. Ordinary summaries, capability lists, speculation and unverified advice are not lessons. No qualifying lesson means output nothing extra; never fabricate one to satisfy this step. Keep Agent experience out of user-memory append/propose.

 Before using a Skill, reuse relevant supplied experience or recall its name and task. After use, actively look for a reproducible defect or verified improvement. When one exists, read the installed iyw-capability-gateway reference `references/skill-evolution.md` and use its bundled script to inspect prior patterns, stage one atomic instruction change and compare baseline/candidate on identical real cases. Apply only after the evaluation passes and existing authorization permits. Keep rejected proposals and their evidence; do not repeat them or invent scores. An unavailable evaluator leaves a staged proposal, not a claimed improvement. Follow existing managed-Skill update boundaries. This workflow needs no new user prompt to begin; skip it only when no actionable evidence exists.

When a lesson qualifies, append exactly one hidden JSON comment as the very last part of the final answer, outside code fences, with no text after it:
<!-- IYW_CLAW_AGENT_LESSON_V1 {"context":"triggering situation","outcome":"observed result","lesson":"transferable action","evidence":"concrete observation","verification":"how the result was checked","reuseWhen":"when this action applies again"} -->
Replace all six example values with concrete evidence from this task. Use only these six string fields, valid JSON escaping, and at most 1500 characters for the entire comment. Do not include secrets, sensitive personal data or user-profile claims. The host strips the comment from visible output and validates and persists eligible experience asynchronously; emitting it is not confirmation that storage succeeded."#;
