[package]
name = "codex-state"
version = "0.155.0"
edition = "2024"
license = "Apache-2.0"
autobins = false
autotests = false
autobenches = false

[lib]
doctest = false

[dependencies.anyhow]
version = "1"

[dependencies.chrono]
version = "0.4.43"

[dependencies.codex-history]
git = "https://github.com/openai/codex.git"
rev = "f0a1b8f0849d90960bc406b848f32e5a129b0457"

[dependencies.codex-protocol]
git = "https://github.com/openai/codex.git"
rev = "f0a1b8f0849d90960bc406b848f32e5a129b0457"

[dependencies.codex-utils-absolute-path]
git = "https://github.com/openai/codex.git"
rev = "f0a1b8f0849d90960bc406b848f32e5a129b0457"

[dependencies.libsqlite3-sys]
version = "0.37"
default-features = false

[dependencies.log]
version = "0.4"

[dependencies.serde]
version = "1"
features = [ "rc", "derive",]

[dependencies.serde_json]
version = "1"

[dependencies.sqlx]
version = "0.9.0"
default-features = false
features = [ "chrono", "json", "macros", "migrate", "runtime-tokio", "tls-rustls", "sqlite-bundled", "time", "uuid",]

[dependencies.strum]
version = "0.27.2"
features = [ "derive",]

[dependencies.tokio]
version = "1"
features = [ "fs", "io-util", "macros", "rt-multi-thread", "sync", "time",]

[dependencies.tracing]
version = "0.1.44"

[dependencies.tracing-subscriber]
version = "0.3.22"

[dependencies.uuid]
version = "1"
