use serde_json::Value;
const MAX_CLIPBOARD_TEXT: usize = 100_000;
const MAX_LAUNCH_NAME: usize = 512;
const MAX_MENU_PATH: usize = 16;
include!("tool_arguments/computer_target_id.rs");
include!("tool_arguments/computer_optional_u32.rs");
include!("tool_arguments/computer_capture_request.rs");
include!("tool_arguments/computer_snapshot_request.rs");
include!("tool_arguments/computer_verify_request.rs");
include!("tool_arguments/computer_ref.rs");
include!("tool_arguments/computer_coordinate.rs");
include!("tool_arguments/computer_generation.rs");
include!("tool_arguments/computer_target.rs");
include!("tool_arguments/computer_modifiers.rs");
include!("tool_arguments/computer_clipboard_op.rs");
include!("tool_arguments/computer_launch_arguments.rs");
include!("tool_arguments/computer_menu_path.rs");
include!("tool_arguments/computer_element.rs");
include!("tool_arguments/computer_choice.rs");
include!("tool_arguments/computer_bool.rs");
include!("tool_arguments/computer_text.rs");
include!("tool_arguments/computer_count.rs");
include!("tool_arguments/computer_act_arguments.rs");
include!("tool_arguments/pointer_actions.rs");
include!("tool_arguments/keyboard_actions.rs");
include!("tool_arguments/window_actions.rs");
include!("tool_arguments/computer_act_request.rs");
