[package]
name = "codex-app-server-client"
version = "0.161.0"
edition = "2024"
license = "Apache-2.0"

[lib]
name = "codex_app_server_client"
path = "src/lib.rs"
doctest = false

[dependencies.codex-app-server]
workspace = true

[dependencies.codex-app-server-protocol]
workspace = true

[dependencies.codex-arg0]
workspace = true

[dependencies.codex-config]
workspace = true

[dependencies.codex-core]
workspace = true

[dependencies.codex-exec-server]
workspace = true

[dependencies.codex-feedback]
workspace = true

[dependencies.codex-protocol]
workspace = true

[dependencies.codex-uds]
workspace = true

[dependencies.codex-utils-absolute-path]
workspace = true

[dependencies.codex-utils-rustls-provider]
workspace = true

[dependencies.futures]
workspace = true

[dependencies.serde]
workspace = true

[dependencies.serde_json]
workspace = true

[dependencies.tokio]
workspace = true
features = [ "sync", "time", "rt",]

[dependencies.tokio-tungstenite]
workspace = true

[dependencies.toml]
workspace = true

[dependencies.tracing]
workspace = true

[dependencies.url]
workspace = true

[workspace.package]
version = "0.156.1"
edition = "2024"
license = "Apache-2.0"

[workspace.dependencies]
serde_json = "1"
tokio = "1"
toml = "0.9.5"
tracing = "0.1.44"
url = "2"

[workspace.dependencies.codex-app-server]
path = "../codex-app-server"

[workspace.dependencies.codex-app-server-protocol]
path = "../codex-app-server-protocol"

[workspace.dependencies.codex-arg0]
git = "https://github.com/openai/codex.git"
rev = "979011409de0a60b52f179721948e65531d26144"
package = "codex-arg0"

[workspace.dependencies.codex-config]
git = "https://github.com/openai/codex.git"
rev = "979011409de0a60b52f179721948e65531d26144"
package = "codex-config"

[workspace.dependencies.codex-core]
path = "../codex-core"

[workspace.dependencies.codex-exec-server]
path = "../codex-exec-server"

[workspace.dependencies.codex-feedback]
git = "https://github.com/openai/codex.git"
rev = "979011409de0a60b52f179721948e65531d26144"
package = "codex-feedback"

[workspace.dependencies.codex-protocol]
path = "../codex-protocol"

[workspace.dependencies.codex-uds]
git = "https://github.com/openai/codex.git"
rev = "979011409de0a60b52f179721948e65531d26144"
package = "codex-uds"

[workspace.dependencies.codex-utils-absolute-path]
git = "https://github.com/openai/codex.git"
rev = "979011409de0a60b52f179721948e65531d26144"
package = "codex-utils-absolute-path"

[workspace.dependencies.codex-utils-rustls-provider]
git = "https://github.com/openai/codex.git"
rev = "979011409de0a60b52f179721948e65531d26144"
package = "codex-utils-rustls-provider"

[workspace.dependencies.futures]
version = "0.3"
default-features = false

[workspace.dependencies.serde]
version = "1"
features = [ "rc",]

[workspace.dependencies.tokio-tungstenite]
git = "https://github.com/openai-oss-forks/tokio-tungstenite"
rev = "0e5b2d73aa18dd9f0a50ee9ff199d5aef7594186"
features = [ "proxy", "rustls-tls-native-roots",]
