// codeg v0.34.0 的生产逻辑；由原模块统一导出。
#[allow(unused_imports)]
use super::*;

/// UI Automation's control types, as cua-driver names them in its Windows
/// tree.
pub(super) const UIA_CONTROL_TYPES: &[&str] = &[
    "AppBar",
    "Button",
    "Calendar",
    "CheckBox",
    "ComboBox",
    "Custom",
    "DataGrid",
    "DataItem",
    "Document",
    "Edit",
    "Group",
    "Header",
    "HeaderItem",
    "Hyperlink",
    "Image",
    "List",
    "ListItem",
    "Menu",
    "MenuBar",
    "MenuItem",
    "Pane",
    "ProgressBar",
    "RadioButton",
    "ScrollBar",
    "SemanticZoom",
    "Separator",
    "Slider",
    "Spinner",
    "SplitButton",
    "StatusBar",
    "Tab",
    "TabItem",
    "Table",
    "Text",
    "Thumb",
    "TitleBar",
    "ToolBar",
    "ToolTip",
    "Tree",
    "TreeItem",
    "Unknown",
    "Window",
];
