use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        add_agent_setting_columns(manager).await?;
        create_agent_installations(manager).await?;
        create_managed_tool_settings(manager).await?;
        create_managed_tool_installations(manager).await
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(
                Table::drop()
                    .table(ManagedToolInstallation::Table)
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(Table::drop().table(ManagedToolSetting::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(AgentInstallation::Table).to_owned())
            .await
    }
}

async fn add_agent_setting_columns(manager: &SchemaManager<'_>) -> Result<(), DbErr> {
    for column in [
        ColumnDef::new(AgentSetting::PinnedVersion)
            .string()
            .null()
            .to_owned(),
        ColumnDef::new(AgentSetting::LastKnownGoodVersion)
            .string()
            .null()
            .to_owned(),
        ColumnDef::new(AgentSetting::UpdateChannel)
            .string()
            .not_null()
            .default("stable")
            .to_owned(),
        ColumnDef::new(AgentSetting::UpdatePolicy)
            .string()
            .not_null()
            .default("recommended")
            .to_owned(),
        ColumnDef::new(AgentSetting::CatalogRevision)
            .big_integer()
            .not_null()
            .default(0)
            .to_owned(),
        ColumnDef::new(AgentSetting::ActivationGeneration)
            .big_integer()
            .not_null()
            .default(0)
            .to_owned(),
    ] {
        manager
            .alter_table(
                Table::alter()
                    .table(AgentSetting::Table)
                    .add_column(column)
                    .to_owned(),
            )
            .await?;
    }
    Ok(())
}

async fn create_agent_installations(manager: &SchemaManager<'_>) -> Result<(), DbErr> {
    manager
        .create_table(
            Table::create()
                .table(AgentInstallation::Table)
                .if_not_exists()
                .col(
                    ColumnDef::new(AgentInstallation::Id)
                        .integer()
                        .not_null()
                        .auto_increment()
                        .primary_key(),
                )
                .col(
                    ColumnDef::new(AgentInstallation::AgentType)
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(AgentInstallation::RegistryId)
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(AgentInstallation::Version)
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(AgentInstallation::Platform)
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(AgentInstallation::Status)
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(AgentInstallation::DeliveryKind)
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(AgentInstallation::ArtifactId)
                        .string()
                        .null(),
                )
                .col(ColumnDef::new(AgentInstallation::SourceKey).string().null())
                .col(
                    ColumnDef::new(AgentInstallation::ExpectedSha256)
                        .string()
                        .null(),
                )
                .col(
                    ColumnDef::new(AgentInstallation::Verified)
                        .boolean()
                        .not_null()
                        .default(false),
                )
                .col(
                    ColumnDef::new(AgentInstallation::FailureCode)
                        .string()
                        .null(),
                )
                .col(
                    ColumnDef::new(AgentInstallation::InstalledAt)
                        .timestamp_with_time_zone()
                        .null(),
                )
                .col(
                    ColumnDef::new(AgentInstallation::VerifiedAt)
                        .timestamp_with_time_zone()
                        .null(),
                )
                .col(
                    ColumnDef::new(AgentInstallation::ActivatedAt)
                        .timestamp_with_time_zone()
                        .null(),
                )
                .col(
                    ColumnDef::new(AgentInstallation::LastSuccessfulLaunchAt)
                        .timestamp_with_time_zone()
                        .null(),
                )
                .col(
                    ColumnDef::new(AgentInstallation::CreatedAt)
                        .timestamp_with_time_zone()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(AgentInstallation::UpdatedAt)
                        .timestamp_with_time_zone()
                        .not_null(),
                )
                .to_owned(),
        )
        .await?;
    manager
        .create_index(
            Index::create()
                .name("idx_agent_installation_unique")
                .table(AgentInstallation::Table)
                .col(AgentInstallation::AgentType)
                .col(AgentInstallation::Version)
                .col(AgentInstallation::Platform)
                .unique()
                .to_owned(),
        )
        .await
}

async fn create_managed_tool_settings(manager: &SchemaManager<'_>) -> Result<(), DbErr> {
    manager
        .create_table(
            Table::create()
                .table(ManagedToolSetting::Table)
                .if_not_exists()
                .col(
                    ColumnDef::new(ManagedToolSetting::Id)
                        .integer()
                        .not_null()
                        .auto_increment()
                        .primary_key(),
                )
                .col(
                    ColumnDef::new(ManagedToolSetting::ToolId)
                        .string()
                        .not_null()
                        .unique_key(),
                )
                .col(
                    ColumnDef::new(ManagedToolSetting::UpdateChannel)
                        .string()
                        .not_null()
                        .default("stable"),
                )
                .col(
                    ColumnDef::new(ManagedToolSetting::PinnedVersion)
                        .string()
                        .null(),
                )
                .col(
                    ColumnDef::new(ManagedToolSetting::ActiveVersion)
                        .string()
                        .null(),
                )
                .col(
                    ColumnDef::new(ManagedToolSetting::LastKnownGoodVersion)
                        .string()
                        .null(),
                )
                .col(
                    ColumnDef::new(ManagedToolSetting::UpdatePolicy)
                        .string()
                        .not_null()
                        .default("recommended"),
                )
                .col(
                    ColumnDef::new(ManagedToolSetting::CatalogRevision)
                        .big_integer()
                        .not_null()
                        .default(0),
                )
                .col(
                    ColumnDef::new(ManagedToolSetting::ActivationGeneration)
                        .big_integer()
                        .not_null()
                        .default(0),
                )
                .col(
                    ColumnDef::new(ManagedToolSetting::CreatedAt)
                        .timestamp_with_time_zone()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(ManagedToolSetting::UpdatedAt)
                        .timestamp_with_time_zone()
                        .not_null(),
                )
                .to_owned(),
        )
        .await
}

async fn create_managed_tool_installations(manager: &SchemaManager<'_>) -> Result<(), DbErr> {
    manager
        .create_table(
            Table::create()
                .table(ManagedToolInstallation::Table)
                .if_not_exists()
                .col(
                    ColumnDef::new(ManagedToolInstallation::Id)
                        .integer()
                        .not_null()
                        .auto_increment()
                        .primary_key(),
                )
                .col(
                    ColumnDef::new(ManagedToolInstallation::ToolId)
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(ManagedToolInstallation::Version)
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(ManagedToolInstallation::Runtime)
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(ManagedToolInstallation::Target)
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(ManagedToolInstallation::Arch)
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(ManagedToolInstallation::Origin)
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(ManagedToolInstallation::Status)
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(ManagedToolInstallation::ArtifactId)
                        .string()
                        .null(),
                )
                .col(
                    ColumnDef::new(ManagedToolInstallation::ExpectedSha256)
                        .string()
                        .null(),
                )
                .col(
                    ColumnDef::new(ManagedToolInstallation::Verified)
                        .boolean()
                        .not_null()
                        .default(false),
                )
                .col(
                    ColumnDef::new(ManagedToolInstallation::FailureCode)
                        .string()
                        .null(),
                )
                .col(
                    ColumnDef::new(ManagedToolInstallation::InstalledAt)
                        .timestamp_with_time_zone()
                        .null(),
                )
                .col(
                    ColumnDef::new(ManagedToolInstallation::VerifiedAt)
                        .timestamp_with_time_zone()
                        .null(),
                )
                .col(
                    ColumnDef::new(ManagedToolInstallation::ActivatedAt)
                        .timestamp_with_time_zone()
                        .null(),
                )
                .col(
                    ColumnDef::new(ManagedToolInstallation::LastSuccessfulUseAt)
                        .timestamp_with_time_zone()
                        .null(),
                )
                .col(
                    ColumnDef::new(ManagedToolInstallation::CreatedAt)
                        .timestamp_with_time_zone()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(ManagedToolInstallation::UpdatedAt)
                        .timestamp_with_time_zone()
                        .not_null(),
                )
                .to_owned(),
        )
        .await?;
    manager
        .create_index(
            Index::create()
                .name("idx_managed_tool_installation_unique")
                .table(ManagedToolInstallation::Table)
                .col(ManagedToolInstallation::ToolId)
                .col(ManagedToolInstallation::Version)
                .col(ManagedToolInstallation::Runtime)
                .col(ManagedToolInstallation::Target)
                .col(ManagedToolInstallation::Arch)
                .col(ManagedToolInstallation::Origin)
                .unique()
                .to_owned(),
        )
        .await
}

#[derive(DeriveIden)]
enum AgentSetting {
    Table,
    PinnedVersion,
    LastKnownGoodVersion,
    UpdateChannel,
    UpdatePolicy,
    CatalogRevision,
    ActivationGeneration,
}
#[derive(DeriveIden)]
enum AgentInstallation {
    Table,
    Id,
    AgentType,
    RegistryId,
    Version,
    Platform,
    Status,
    DeliveryKind,
    ArtifactId,
    SourceKey,
    ExpectedSha256,
    Verified,
    FailureCode,
    InstalledAt,
    VerifiedAt,
    ActivatedAt,
    LastSuccessfulLaunchAt,
    CreatedAt,
    UpdatedAt,
}
#[derive(DeriveIden)]
enum ManagedToolSetting {
    Table,
    Id,
    ToolId,
    UpdateChannel,
    PinnedVersion,
    ActiveVersion,
    LastKnownGoodVersion,
    UpdatePolicy,
    CatalogRevision,
    ActivationGeneration,
    CreatedAt,
    UpdatedAt,
}
#[derive(DeriveIden)]
enum ManagedToolInstallation {
    Table,
    Id,
    ToolId,
    Version,
    Runtime,
    Target,
    Arch,
    Origin,
    Status,
    ArtifactId,
    ExpectedSha256,
    Verified,
    FailureCode,
    InstalledAt,
    VerifiedAt,
    ActivatedAt,
    LastSuccessfulUseAt,
    CreatedAt,
    UpdatedAt,
}
