[package]
name = "codex-chatgpt"
version = "0.161.0"
edition = "2024"
license = "Apache-2.0"
autobins = false
autotests = false
autobenches = false

[lib]
path = "src/lib.rs"
doctest = false

[dependencies.anyhow]
version = "1"

[dependencies.clap]
version = "4"
features = [ "derive",]

[dependencies.codex-connectors]
git = "https://github.com/openai/codex.git"
rev = "979011409de0a60b52f179721948e65531d26144"

[dependencies.codex-core]
git = "https://github.com/openai/codex.git"
rev = "979011409de0a60b52f179721948e65531d26144"

[dependencies.codex-git-utils]
git = "https://github.com/openai/codex.git"
rev = "979011409de0a60b52f179721948e65531d26144"

[dependencies.codex-http-client]
git = "https://github.com/openai/codex.git"
rev = "979011409de0a60b52f179721948e65531d26144"

[dependencies.codex-login]
git = "https://github.com/openai/codex.git"
rev = "979011409de0a60b52f179721948e65531d26144"

[dependencies.codex-model-provider]
git = "https://github.com/openai/codex.git"
rev = "979011409de0a60b52f179721948e65531d26144"

[dependencies.codex-plugin]
git = "https://github.com/openai/codex.git"
rev = "979011409de0a60b52f179721948e65531d26144"

[dependencies.codex-utils-cli]
git = "https://github.com/openai/codex.git"
rev = "979011409de0a60b52f179721948e65531d26144"

[dependencies.serde]
version = "1"
features = [ "rc", "derive",]

[dependencies.tokio]
version = "1"
features = [ "full",]
